In [324]:
import torch

In [325]:
# Create a empty tensor
x = torch.empty(5, 3)
print(x)

tensor([[9.9115e+27, 9.9913e-43, 1.9339e-01],
        [2.3658e+00, 8.7089e-01, 1.2255e+00],
        [7.9400e-01, 2.3253e-01, 2.2223e+00],
        [8.8912e-02, 1.6132e+00, 1.2027e-01],
        [5.1996e-01, 1.1060e+00, 1.9671e+00]])


In [326]:
# Create a long tensor
x = torch.zeros(5,3, dtype=torch.long)
print(x.dtype)
print(x)

torch.int64
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [327]:
# Use a list to create tensor
x = torch.tensor([1, 3])
print(x.shape, x.dtype)
print(x)

torch.Size([2]) torch.int64
tensor([1, 3])


In [328]:
# Create tensor by existed tensor
x = x.new_ones(3, 3)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [329]:
print(x.size())
print(x.shape)

torch.Size([3, 3])
torch.Size([3, 3])


In [330]:
# Add tensor
x = torch.randn(5, 3, dtype=torch.float)
y = torch.randn(5, 3, dtype=torch.float)
print(x)
print(y)

tensor([[-1.5981,  0.4472,  0.9416],
        [-2.5022,  0.8840,  1.8454],
        [-0.5461, -0.1828, -1.6334],
        [ 0.3549, -0.3468, -0.0526],
        [ 1.4375, -0.8539, -0.2610]])
tensor([[-0.7521,  0.7046,  0.9909],
        [ 1.7475,  0.0053,  1.2987],
        [ 1.2493,  1.1902,  0.1833],
        [ 0.9343, -0.8761,  0.2176],
        [ 1.0887, -2.0792, -0.4199]])


In [331]:
print(x+y)

tensor([[-2.3502,  1.1518,  1.9325],
        [-0.7547,  0.8893,  3.1441],
        [ 0.7032,  1.0074, -1.4501],
        [ 1.2892, -1.2228,  0.1650],
        [ 2.5262, -2.9331, -0.6809]])


In [332]:
print(torch.add(x,y))

tensor([[-2.3502,  1.1518,  1.9325],
        [-0.7547,  0.8893,  3.1441],
        [ 0.7032,  1.0074, -1.4501],
        [ 1.2892, -1.2228,  0.1650],
        [ 2.5262, -2.9331, -0.6809]])


In [333]:
result = torch.zeros(5, 3)
torch.add(x,y,out=result)
print(result)

tensor([[-2.3502,  1.1518,  1.9325],
        [-0.7547,  0.8893,  3.1441],
        [ 0.7032,  1.0074, -1.4501],
        [ 1.2892, -1.2228,  0.1650],
        [ 2.5262, -2.9331, -0.6809]])


In [334]:
result = torch.ones(5, 3)
torch.add(x,y,out=result)   # replace the value of result
print(result)

tensor([[-2.3502,  1.1518,  1.9325],
        [-0.7547,  0.8893,  3.1441],
        [ 0.7032,  1.0074, -1.4501],
        [ 1.2892, -1.2228,  0.1650],
        [ 2.5262, -2.9331, -0.6809]])


In [335]:
y.add_(x)   # change y
print(y)

tensor([[-2.3502,  1.1518,  1.9325],
        [-0.7547,  0.8893,  3.1441],
        [ 0.7032,  1.0074, -1.4501],
        [ 1.2892, -1.2228,  0.1650],
        [ 2.5262, -2.9331, -0.6809]])


In [336]:
# indices in tensor
# shared memory with origin tensor
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [337]:
y = x[0, :]
y

tensor([1., 1., 1.])

In [338]:
y += 1
y

tensor([2., 2., 2.])

In [339]:
x

tensor([[2., 2., 2.],
        [1., 1., 1.]])

In [340]:
y = y + 1
y

tensor([3., 3., 3.])

In [341]:
x   # "y = y + 1" will create a new tensor

tensor([[2., 2., 2.],
        [1., 1., 1.]])

In [342]:
# Change shape by view (share memory)
x = torch.ones(4, 4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [343]:
y = x.view(2, 8)
y

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [344]:
y += 1
print(y)
print(x)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [345]:
y = y + 1
print(y)
print(x)

tensor([[3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [346]:
# copy tensor
x = torch.ones(2, 8)
x

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [347]:
y = x.clone().view(4, 4)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [348]:
# x.clone() don't share memory with x
y += 1
print(y)
print(x)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [349]:
# translate tensor to a python number
x = torch.tensor(1, dtype=torch.long)
print(x)
print(x.item())

tensor(1)
1


In [350]:
# broadcast in pytorch
x = torch.arange(1, 3).view(1, 2)
print(x)

y = torch.arange(1, 4).view(3, 1)
print(y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])


In [351]:
# x  +  y    ---> (1, 2) + (3, 1)
# [[1, 2]   +  [[1, 1]
#  [1, 2]       [2, 2]
#  [1, 2]]      [3, 3]]
# (1, 2) -> (3, 2) ; (3, 1) -> (3, 2)
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

In [352]:
# memory in tensor
x = torch.ones(2, 2)
y = torch.zeros(2, 2)
id_pre = id(y)
y = y + x
id_la = id(y)
print(id_la == id_pre)

False


In [353]:
# use indices to fix memory
x = torch.ones(2, 2)
y = torch.zeros(2, 2)
id_pre = id(y)
y[:] = y + x    # y[:] share the same memory with y
id_la = id(y)
print(id_la == id_pre)

True


In [354]:
# translate tensor to / from numpy (share memory)
import numpy as np
x = np.arange(1, 3)
print(x)

[1 2]


In [355]:
y = torch.from_numpy(x)
print(y)
y += 1
print(x)
print(y)

tensor([1, 2], dtype=torch.int32)
[2 3]
tensor([2, 3], dtype=torch.int32)


In [356]:
y = torch.ones(1, 3)
x = y.numpy()
print(y)
print(x)
print('------')
x += 1
print(y)
print(x)

tensor([[1., 1., 1.]])
[[1. 1. 1.]]
------
tensor([[2., 2., 2.]])
[[2. 2. 2.]]


In [357]:
# device
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.zeros((3, 5), device=device)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')


In [358]:
y = torch.arange(5)
print(y)

tensor([0, 1, 2, 3, 4])


In [359]:
print(x + y.to(device))

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]], device='cuda:0')


In [360]:
x = torch.tensor([1, 2, 3], dtype=torch.float, requires_grad=True)
y = torch.tensor([1, 2], dtype=torch.float ,requires_grad=True).view(2, 1)
a = torch.tensor([1, 2, 1, 2, 1, 2], dtype=torch.float, requires_grad=True).view(3, 2)
y.retain_grad()
a.retain_grad()

print(x)
print(y)
z = x + y   
z.retain_grad()
print(z)
print(z.shape, z.dtype)

tensor([1., 2., 3.], requires_grad=True)
tensor([[1.],
        [2.]], grad_fn=<ViewBackward0>)
tensor([[2., 3., 4.],
        [3., 4., 5.]], grad_fn=<AddBackward0>)
torch.Size([2, 3]) torch.float32


In [361]:
print(a.shape, a.dtype)
print(a)

torch.Size([3, 2]) torch.float32
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]], grad_fn=<ViewBackward0>)


In [362]:
l = z @ a
l.retain_grad()
print(l)

tensor([[ 9., 18.],
        [12., 24.]], grad_fn=<MmBackward0>)


In [363]:
result = l.mean()
print(result)

tensor(15.7500, grad_fn=<MeanBackward0>)


In [364]:
result.backward()

In [369]:
print(x.grad)
print(y.grad)
print(z.grad)
print(a.grad)
print(l.grad)

tensor([1.5000, 1.5000, 1.5000])
tensor([[2.2500],
        [2.2500]])
tensor([[0.7500, 0.7500, 0.7500],
        [0.7500, 0.7500, 0.7500]])
tensor([[1.2500, 1.2500],
        [1.7500, 1.7500],
        [2.2500, 2.2500]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [372]:
# l = z @ a
# dz = dl @ a.T  ; da = z.T @ dl
print(l.grad @ a.T)
print(z.T @ l.grad)

# z = x + y   : z(2, 3), x(1, 3), y(2, 1)
# dx = dz = dy (consider the shape!!!)
print(z.grad.sum(0, keepdim=True))
print(z.grad.sum(1, keepdim=True))

tensor([[0.7500, 0.7500, 0.7500],
        [0.7500, 0.7500, 0.7500]], grad_fn=<MmBackward0>)
tensor([[1.2500, 1.2500],
        [1.7500, 1.7500],
        [2.2500, 2.2500]], grad_fn=<MmBackward0>)
tensor([[1.5000, 1.5000, 1.5000]])
tensor([[2.2500],
        [2.2500]])


In [377]:
x = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float, requires_grad=True).view(2, 3)
y = torch.tensor([6, 5, 4, 3, 2, 1], dtype=torch.float, requires_grad=True).view(2, 3)
z = x * y
parameters = [x, y, z]
for p in parameters:
    p.retain_grad()

result = z.sum()
print(x)
print(y)
print(z)

tensor([[1., 2., 3.],
        [4., 5., 6.]], grad_fn=<ViewBackward0>)
tensor([[6., 5., 4.],
        [3., 2., 1.]], grad_fn=<ViewBackward0>)
tensor([[ 6., 10., 12.],
        [12., 10.,  6.]], grad_fn=<MulBackward0>)


In [378]:
# z[i, j] = x[i, j] * y[i, j]
# dx[i, j] = y[i, j] ; dy[i, j] = x[i, j]

result.backward()
print(z.grad)
print(y.grad)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[6., 5., 4.],
        [3., 2., 1.]])


In [381]:
# tensor.data is beside DAG
x = torch.tensor([1], dtype=torch.float, requires_grad=True)
print(x.data.requires_grad)

False
