In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [80]:
# Read dataset
with open('Datasets/JayChouLyrics/jaychou_lyrics.txt', 'r', encoding='utf-8') as lyrics:
    data = lyrics.read()

data = data[:10000]
data = data.replace('\n', ' ')
chars = sorted(list(set(data)))
vocab_size = len(chars)

stoi = {s:i for i, s in enumerate(chars)}
itos = {i:s for s, i in stoi.items()}


print(''.join(s for s in data[:20]))
print(list(stoi[s] for s in data[:20]))

想要有直升机 想要和你飞到宇宙去 想要和
[403, 862, 506, 696, 149, 513, 0, 403, 862, 201, 84, 1000, 128, 286, 290, 161, 0, 403, 862, 201]


In [39]:
# Sample
import random
random.seed(42)

# Random sampling from datasets
def randomSample(data, batch_size, num_steps):
    num_sample = (len(data) - num_steps) // batch_size * batch_size
    idx_sample = list(range(num_sample))
    random.shuffle(idx_sample)
    epoch_size = num_sample // batch_size
    
    # create an iter
    for i in range(epoch_size):
        idx = i * epoch_size
        batch_idx = idx_sample[idx : idx+batch_size]
        X = [data[n : n+num_steps] for n in batch_idx]
        y = [data[n+1 : n+num_steps+1] for n in batch_idx]
        yield torch.tensor(X), torch.tensor(y)

# Sequential sampling
def sequentialSample(data, batch_size, num_steps):
    num_sample = (len(data) - num_steps) // batch_size * batch_size
    idx_sample = list(range(num_sample))
    epoch_size = num_sample // batch_size
    
    # create an iter
    for i in range(epoch_size):
        idx = i * epoch_size
        batch_idx = idx_sample[idx : idx+batch_size]
        X = [data[n : n+num_steps] for n in batch_idx]
        y = [data[n+1 : n+num_steps+1] for n in batch_idx]
        yield torch.tensor(X), torch.tensor(y)

In [40]:
a = randomSample([1,2,3,4,5,6,7,8], 2, 5)
for X, y in a:
    print(X)
    print(y)

a = sequentialSample([1,2,3,4,5,6,7,8], 2, 5)
for X, y in a:
    print(X)
    print(y)

tensor([[2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5]])
tensor([[3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6]])
tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])
tensor([[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]])


In [8]:
len([1, 1, 1])

3