In [3]:
import torch
from torch import nn

x = torch.ones(3)
torch.save(x, 'x.pt')

In [5]:
x2 = torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [6]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

# 读写模型

In [9]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)
    
    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)
    
net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.5416,  0.4052,  0.2972],
                      [-0.1600, -0.1361, -0.2913]])),
             ('hidden.bias', tensor([ 0.3412, -0.1092])),
             ('output.weight', tensor([[ 0.3255, -0.0728]])),
             ('output.bias', tensor([0.5287]))])

In [10]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001,
momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'fused': None,
   'params': [0, 1, 2, 3]}]}

# 保存与加载模型

In [11]:
X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])