In [2]:
import torch
from torch import nn

torch.cuda.is_available()   # GPU是否可用

True

In [3]:
torch.cuda.device_count()   # 查看GPU的数量

1

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

# Tensor 的GPU计算

In [8]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [10]:
x = x.cuda(0) # 将CPU上的Tensor复制到GPU上，i表示第i块GPU
x

tensor([1, 2, 3], device='cuda:0')

In [12]:
x.device # 查看Tensor所在的设备

device(type='cuda', index=0)

In [14]:
# 在创建的时候制定设备
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([1, 2, 3], device=device)
x = torch.tensor([1, 2, 3]).to(device)  # 跟上面是相同的效果
x

tensor([1, 2, 3], device='cuda:0')

In [16]:
y = x ** 2      # GPU上的数字和CPU上的数字不可以直接计算
y

tensor([1, 4, 9], device='cuda:0')

# 模型的GPU计算

In [17]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [18]:
net.cuda()
list(net.parameters())[0].device    # 所以我们需要保证输入的Tensor和模型在同一个device上

device(type='cuda', index=0)