In [2]:
import numpy as np
import torch

# Creation

## Create Tensor without initialization

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.2121e-27, 9.7671e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


## Create random Tensor(5*3)

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.7823, 0.5883, 0.3438],
        [0.7569, 0.0460, 0.9075],
        [0.2286, 0.5273, 0.5097],
        [0.7736, 0.1189, 0.6827],
        [0.4065, 0.1580, 0.4392]])


## Create Tensor (long type)

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## Create Tensor with initialization

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


## Create Tensor with existed Tensor

In [7]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.5295, 0.7717, 0.9387],
        [0.1008, 0.3664, 0.4962],
        [0.7181, 0.6410, 0.7382],
        [0.8200, 0.8480, 0.4847],
        [0.6139, 0.2712, 0.4234]])


## Get Tensor's shape

In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


# Operation

## Arithmetical operation

In [10]:
# way 1
y = torch.rand(5,3)
print(x + y)

tensor([[0.9635, 1.5643, 1.0696],
        [1.0912, 0.6910, 1.3740],
        [1.6493, 1.1786, 1.2128],
        [1.4716, 1.0451, 0.7640],
        [1.4096, 0.4998, 0.7226]])


In [11]:
# way 2
print(torch.add(x, y))

tensor([[0.9635, 1.5643, 1.0696],
        [1.0912, 0.6910, 1.3740],
        [1.6493, 1.1786, 1.2128],
        [1.4716, 1.0451, 0.7640],
        [1.4096, 0.4998, 0.7226]])


In [12]:
# point the output the add
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9635, 1.5643, 1.0696],
        [1.0912, 0.6910, 1.3740],
        [1.6493, 1.1786, 1.2128],
        [1.4716, 1.0451, 0.7640],
        [1.4096, 0.4998, 0.7226]])


In [13]:
# way 3 Inplace, like method in an object, change the object itself
y.add_(x)   
print(y)

tensor([[0.9635, 1.5643, 1.0696],
        [1.0912, 0.6910, 1.3740],
        [1.6493, 1.1786, 1.2128],
        [1.4716, 1.0451, 0.7640],
        [1.4096, 0.4998, 0.7226]])


## Index


In [14]:
# like operations in Numpy, the index result shares same memory with original data
y = x[0, :]
print(x[0, :])

tensor([0.5295, 0.7717, 0.9387])


In [15]:
y += 1
print(x[0, :])

tensor([1.5295, 1.7717, 1.9387])


## Change shape

In [16]:
y = x.view(15)  # share the same memory, actually same tensor
print(y)

tensor([1.5295, 1.7717, 1.9387, 0.1008, 0.3664, 0.4962, 0.7181, 0.6410, 0.7382,
        0.8200, 0.8480, 0.4847, 0.6139, 0.2712, 0.4234])


In [17]:
x += 1
print(x)
print(y)

tensor([[2.5295, 2.7717, 2.9387],
        [1.1008, 1.3664, 1.4962],
        [1.7181, 1.6410, 1.7382],
        [1.8200, 1.8480, 1.4847],
        [1.6139, 1.2712, 1.4234]])
tensor([2.5295, 2.7717, 2.9387, 1.1008, 1.3664, 1.4962, 1.7181, 1.6410, 1.7382,
        1.8200, 1.8480, 1.4847, 1.6139, 1.2712, 1.4234])


## Deep Copy(no sharing memory)

In [18]:
x_cp = x.clone().view(15)   # when gradient go back to x_cp, will back to x same time
x -= 1
print(x)
print(x_cp)

tensor([[1.5295, 1.7717, 1.9387],
        [0.1008, 0.3664, 0.4962],
        [0.7181, 0.6410, 0.7382],
        [0.8200, 0.8480, 0.4847],
        [0.6139, 0.2712, 0.4234]])
tensor([2.5295, 2.7717, 2.9387, 1.1008, 1.3664, 1.4962, 1.7181, 1.6410, 1.7382,
        1.8200, 1.8480, 1.4847, 1.6139, 1.2712, 1.4234])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())     # change tensor to python number

tensor([0.3316])
0.3316407799720764


## Linear Algebra

In [20]:
# 参考官方文档看

## Broadcast

In [21]:
# 2 tensor with different shape add, change to same shape then add.
x = torch.arange(1,3).view(1,2)     # like range in python
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## Memory overhead in arithmetical operation

In [22]:
x = torch.tensor([1,2])     # when add .view(1,2) , will become [[]] not []
y = torch.tensor([3,4])
id_before = id(y)   # show the memory address
y = y + x
print(id(y) == id_before)

False


In [23]:
# new memory point original place
x = torch.tensor([1,2])    
y = torch.tensor([3,4])
id_before = id(y)
y[:] = y + x        # torch.add(x,y,out=y),y+=x,y.add_(x)  same
print(id(y) == id_before)

True


## Interconversion between tensor & numpy

In [24]:
# numpy() and from_numpy(), share same memory

# tensor to numpy
a = torch.ones(5)
b = a.numpy()
print(a,b)

a += 1
print(a,b)

b += 1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [25]:
# numpy to tensor
# all tensor on cpu is available for interconversion
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)  # torch.tensor(np) work as well, but doesn't share memory
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [26]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## Tensor on GPU


In [27]:
# use to() to move Tensor between CPU and GPU
if torch.cuda.is_available():
    device = torch.device('cuda')   
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


# Automatic gradient finding

In [28]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)    # is this tensor created by some calculation

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [31]:
y = x + 2   # x is Leaf Node , its grad_fn is None
print(y)
print(y.grad_fn)    # x + 2 !

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [32]:
print(x.is_leaf,y.is_leaf)

True False
