In [6]:
import torch

# leaf
x = torch.ones(2,2,requires_grad=True)  # create a tensor with grad
print(x)
print(x.grad_fn)    # gradient function

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


# Tensor

In [7]:
y = x + 2   
print(y)
print(y.grad_fn)    # y = x + 2 ,created by "+", so has grad_fn

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
print(x.is_leaf, y.is_leaf)

True False


In [9]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2,2)
a = ((a * 3)/(a - 1))
print(a.requires_grad)
a.requires_grad = True
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


# Gradient

In [11]:
out.backward()

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [15]:
out3 = x.sum()
x.grad.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [16]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)


In [17]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)


tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [24]:
x = torch.tensor(1.0, requires_grad=True,dtype=torch.float)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3

y3 = y1 + y2
print(x.requires_grad)
print(y1,y1.requires_grad)  
print(y2,y2.requires_grad)  
print(y3,y3.requires_grad)  


True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [25]:
y3.backward()
print(x.grad)

tensor(2.)


In [30]:
x = torch.ones(1, requires_grad=True)
print(x.data)
print(x.data.requires_grad)

y = 2 * x
x.data *= 100

y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
